### ISSUE TITLE
Multipart/form-data streaming

### ISSUE THREAD

**Issue by Magiguigui** [mcritz/VaporUploads#1]
Thank for your repo !

Do you have hints or idea to make it work with html form ? 

If I apply the concept of your `upload` method that's the result in the file :

```txt
------WebKitFormBoundaryS8dKJ3QU3BqvOObI
Content-Disposition: form-data; name="title"

title
------WebKitFormBoundaryS8dKJ3QU3BqvOObI
Content-Disposition: form-data; name="file"; filename="message.txt"
Content-Type: text/plain

...
content
...
------WebKitFormBoundaryS8dKJ3QU3BqvOObI--
```

I have absolutely no idea how to handle this two things. First handling form content payload and then stream the file.
Perhaps it's not even the write way to do it ?

**Comment by mcritz** [comment]
Hi! Great question.

My use case involves streaming a Content-Type of application/octet-stream. I use JavaScript to post my form values as data with Content-Type set in the header.

When I get a chance, I’ll try to provide an example of form encoded upload streaming.

Some things worth looking at would be changing the Content-Type or maybe even the Content-Disposition.

**Comment by mcritz** [comment]
I’ve looked into this some more and I don’t think I can stream a `form/multipart` encoded post. You’ll want to either post using Javascript per my July 6th comment. OR `app.on(.POST, "path", body: .collect(maxSize: SOME_INT_THAT_WORKS), use: handler)`

See my [routes.swift:11](https://github.com/mcritz/VaporUploads/blob/71e2f4cb5bd2fd2b248b828c995bf02a2ed03c21/Sources/App/routes.swift#L11).
